### ISSUE TITLE
Mongodb atlas connection issue after deployment of flows changes.

### ISSUE THREAD

**Issue by SathishAllen** [steineey/node-red-contrib-mongodb4#10]
After deploying the database into mongodb atlas cluster, initially there is no connection issue with mongodb but after deploying the flow changes from node-red, unable to connect with mongodb atlas getting connection error as  "connection 1 to <ip address>:27017 closed".
The connection string used is "mongodb+srv://<username>:<password>@cluster0.xxxx.mongodb.net/<database name>?retryWrites=true&w=majority". 

node-red-contrib-mongodb4 : Latest version (1.7.0).
mongodb : 4.10.0.
node js : 16.16.0.

**Comment by SathishAllen** [comment]
I have tried this solution https://github.com/steineey/node-red-contrib-mongodb4/issues/2#issuecomment-1004341926

**Comment by steineey** [comment]
I think the atlas server is rejecting your connection, because your connection uri is missing username and password.
A valid connection string example looks like this `mongodb+srv://myuser:mypassword@cluster0.xxxx.mongodb.net/?retryWrites=true&w=majority`

With the NodeRED node it's even simpler: \
<img width="577" alt="Bildschirmfoto 2022-09-28 um 19 11 14" src="https://user-images.githubusercontent.com/25723780/192846364-6c0c76b6-5b5b-4347-95ac-5936fd349e7e.png">

The "connection to :27017 closed" error is an error from the native mongodb driver. The nodered node will try to connect to the database server right after flow deployment. The error is thrown during connection, if a connection request failed or timed out.

**Comment by SathishAllen** [comment]
I have tried this connection string "mongodb+srv://username:password@cluster0.pau9t.mongodb.net/database?retryWrites=true&w=majority", but still it's not working.

**Comment by steineey** [comment]
Can you connect to the cluster with other MongoDB clients like MongoDB shell, Robot3t or NoSQLBooster?
I still don't think that this is a problem with the node.

**Comment by SathishAllen** [comment]
Yes, I can connect to the cluster from mongoDB compass. The mongoDB node was successfully connected with cluster for the first time, when the server application starts. The issue came after the deployment of flows changes, till then the node works perfectly.

**Comment by steineey** [comment]
Sry but I can not reproduce your error. Can you send me an example flow.

**Comment by steineey** [comment]
closed after inactivity
