### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by slavomirMatuska** [steineey/node-red-contrib-mongodb4#17]
Hi,

 i`m trying to install this package (v 1.10) in Node-RED and it fails. Node-RED version: 3.0.2, running in docker container. Here are the error logs from the Node-RED: 

2023-03-20T07:24:44.793Z Install : node-red-contrib-mongodb4 1.10.0
2023-03-20T07:24:44.858Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-mongodb4@1.10.0
2023-03-20T07:24:46.670Z [err] npm WARN config production Use `--omit=dev` instead.
2023-03-20T07:25:02.937Z rc=null

And the logs from running docker container:

20 Mar 11:36:42 - [info] Installing module: node-red-contrib-mongodb4, version: 1.10.0
20 Mar 11:37:00 - [warn] Installation of module node-red-contrib-mongodb4 failed:
20 Mar 11:37:00 - [warn] ------------------------------------------
20 Mar 11:37:00 - [warn] npm WARN config production Use `--omit=dev` instead.
20 Mar 11:37:00 - [warn] ------------------------------------------
Error: Install failed
    at /usr/src/node-red/node_modules/@node-red/registry/lib/installer.js:285:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
20 Mar 11:37:00 - [error] Error: Install failed

Thanks for the help

**Comment by steineey** [comment]
﻿Hi,this is a npm warning. This package includes dev dependencies for testing. I think this warning is triggered by a problem with your npm configuration.You can install a npm package and omit dev dependencies.You can install the package with the container shell. It looks like that the node red editor can‘t handle warning.Am 20.03.2023 um 12:48 schrieb slavomirMatuska ***@***.***>:﻿
Hi,
im trying to install this package (v 1.10) in Node-RED and it fails. Node-RED version: 3.0.2, running in docker container. Here are the error logs from the Node-RED:  2023-03-20T07:24:44.793Z Install : node-red-contrib-mongodb4 1.10.0 2023-03-20T07:24:44.858Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict ***@***.*** 2023-03-20T07:24:46.670Z [err] npm WARN config production Use --omit=dev` instead.
2023-03-20T07:25:02.937Z rc=null
And the logs from running docker container:
20 Mar 11:36:42 - [info] Installing module: node-red-contrib-mongodb4, version: 1.10.0
20 Mar 11:37:00 - [warn] Installation of module node-red-contrib-mongodb4 failed:
20 Mar 11:37:00 - [warn] ------------------------------------------
20 Mar 11:37:00 - [warn] npm WARN config production Use --omit=dev instead.
20 Mar 11:37:00 - [warn] ------------------------------------------
Error: Install failed
at ***@***.***/registry/lib/installer.js:285:25
at runMicrotasks ()
at processTicksAndRejections (node:internal/process/task_queues:96:5)
20 Mar 11:37:00 - [error] Error: Install failed
Thanks for the help

**Comment by steineey** [comment]
Okay, I tried to reproduce your error with the docker image `nodered/node-red:3.0.2-minimal`.
I get the same warning with the node-red editor package installer. But it's just a warning the package is installed.
I tried another node-red node package and this throws the same warning.

```
-----------------------------------------------------------
2023-03-23T14:34:54.461Z Install : node-red-contrib-mongodb4 1.10.0

2023-03-23T14:34:54.494Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-mongodb4@1.10.0
2023-03-23T14:34:55.642Z [err] npm WARN config production Use `--omit=dev` instead.
2023-03-23T14:36:06.386Z [out] 
2023-03-23T14:36:06.386Z [out] added 95 packages in 1m
2023-03-23T14:36:06.528Z rc=0

-----------------------------------------------------------
2023-03-23T15:10:19.157Z Install : node-red-dashboard 3.4.0

2023-03-23T15:10:19.238Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-dashboard@3.4.0
2023-03-23T15:10:20.559Z [err] npm
2023-03-23T15:10:20.588Z [err]  WARN config production Use `--omit=dev` instead.
2023-03-23T15:10:39.218Z [out] 
2023-03-23T15:10:39.218Z [out] added 53 packages in 19s
2023-03-23T15:10:39.268Z rc=0
```

The warning is caused by the npm install flag `--production`. Maybe this flag is deprecated.

You can do what the warning says and run this install command with `--omit=dev` instead of `--production`

```
npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --omit=dev --engine-strict node-red-contrib-mongod
b4@1.10.0
```

**Comment by steineey** [comment]
Okay I understand. Yes I have tested the installation with `Manage Palette` but with the `nodered/node-red:3.0.2-minimal` image. The `minimal` image is based on Linux Alpine. You have used the default image which is based on Linux Debian. I use the Linux Alpine version because it has much smaller memory footprint. Maybe the different Linux Distribution behave different.

But If you want to teach a class of students, my suggestion would be to building your own docker node-red image based on the nodered docker image with all additional dependencies and settings pre installed.
Here is an example project: [steineey/node-red-docker](https://github.com/steineey/node-red-docker)

You can publish your custom image to docker hub or github packages. Or use docker save & load cli [more here](https://stackoverflow.com/questions/23935141/how-to-copy-docker-images-from-one-host-to-another-without-using-a-repository)

**Comment by steineey** [comment]
I also tested the 'Manage Palette' Installation with `nodered/node-red:3.0.2`. I get the same warning, but the package is installed.
Issue is closed since there is nothing wrong with this package. The warning is a problem with node-red's npm install.
