### ISSUE TITLE
Automatic Re-connection to MongoDB on Node-RED Startup

### ISSUE THREAD

**Issue by polu-im** [steineey/node-red-contrib-mongodb4#20]
The module allows for proper re-connection to the MongoDB service in the event of a database restart (by the client option config). However, the issue is that if the database is currently unreachable and Node-RED is started, the component throws an error (ping failed) and does not attempt to reconnect later. The only way to resolve this is by redeploying the flows.

In my opinion, this behavior is incorrect. For example, if a machine running Node-RED and MongoDB is restarted, and Node-RED starts before the database, the connection is interrupted, and the MongoDB flows cannot be used until the component is redeployed (or Node-RED is restarted).

In my view, the best approach would be for the component to attempt re-connection every X seconds (perhaps defined in the connection string settings). It's understandable to show a "ping failed" status until MongoDB responds, but the component should continue trying to reconnect. Once the service becomes available, it should automatically establish a connection and display a green status.

In terms of automation, a machine restart could occur, and this component should handle this situation automatically without requiring manual intervention to unlock it.

Thank you for providing such a great Node-RED component! 

Best regards

**Comment by steineey** [comment]
Hi polu-im, 
thank you for reporting this issue. You're right the node should retry to connect to the database in any scenario. I never noticed this, because in my most of my use cases I connect to a MongoDB cluster which is always online. I used the "ping" to check the MongoDB client configuration during development.

I will deliver a fix for that in near future.

Best Regards
Steineey

**Comment by polu-im** [comment]
Hi Steineey,

Thank you for your quick response and for acknowledging the issue. 
Your willingness to deliver a fix are greatly appreciated.

Best regards

**Comment by steineey** [comment]
Hi polu-im,

the latest release (v2.2.1) should fix your issue.

The problem was the Mongodb ping command at flow start. The database command closed the database topology if the ping failed. If the topology is closed a reconnect or a late first connect is impossible. This might be a bug in MongoDB's NodeJS driver. To fix your issue I decided to remove this feature from the node. It is not usual for a database node to check the connection before the first request.

In the latest release the node should work as you expect it. The node will always reconnect. You can set a connect timeout in the MongoDB client node. This means per default the node will wait 30 sec before dropping the request. But it will also try to reconnect on next request.
