### ISSUE TITLE
Prioritize getting values on the panel rather than in the msg variable

### ISSUE THREAD

**Issue by lekhahuynh** [steineey/node-red-contrib-mongodb4#23]
Hello steineey,,
This library is good. I very often use this library in my node-red project.
But I have a problem with library take **operation** and **collection** from msg rather than take from panel config.
I have many flow & node and difficult to control variable in other flow and node so I think so good if you change to priority to get operation and collection of library get value from panel rather than msg variable.
Sorry about my english not good.

Thanks,

**Comment by steineey** [comment]
Hi lekhahuynh,

thank you for your feedback. I think you are absolutely right. Actually, I've always done it that way with my node-red-nodes.

The node properties set via the panel should have higher priority than msg properties. The node should only use a msg property like `msg.operation` if the property in the panel is empty. This is also the behavior of other offical node red nodes like in the http requeset node. The url can be injected with `msg.url` but only if the node url property is empty.

I will adjust this so that this node behaves more node-red like. I plan a release in a few days.

**Comment by lekhahuynh** [comment]
Good news.
Thank you so much

**Comment by steineey** [comment]
I have released `node-red-contrib-mongodb4@2.5.0` on npm. This should fix your issue with this package.
