### ISSUE TITLE
Version 2.3 vs 2.5

### ISSUE THREAD

**Issue by wiehannvanzyl** [steineey/node-red-contrib-mongodb4#24]
Hi, many thanks for this node - very helpful. 

I'm currently running version 2.3 on Node Red, had some challenges to get it up and running because the initial setup is not very clear and MongoDB imposes restrictions on free tiers like only allowing SCRAM-SHA-1. An example would be very helpful in this regard - showing setup for both Simple and Advanced connections. 

My issue today...jsut installed on another instance of Node Red version 2.5 and duplicated the exact same creditials and it is giving an error. The 2.3 instance is still running fine. 

Has anything changed in this regard or am I missing something obvious? 

Many thanks!

**Comment by steineey** [comment]
Hi wiehannvanzyl,

thank you for using this node.

From node-red-contrib-mongodb4 v2.3 to v2.5 the mongodb driver was upgrade from v5.6 to v5.9 to support the latest mongodb server v7. Read more about other changes [here](https://github.com/steineey/node-red-contrib-mongodb4/releases), but I don't think that these changed breaking your instance.

Here's a configuration example:

<img width="581" alt="Bildschirmfoto 2023-11-09 um 21 04 59" src="https://github.com/steineey/node-red-contrib-mongodb4/assets/25723780/ff38b393-1a0c-49fd-b035-4ad984c97f8b">

<img width="623" alt="Bildschirmfoto 2023-11-09 um 21 02 48" src="https://github.com/steineey/node-red-contrib-mongodb4/assets/25723780/8329ab24-a52e-48bf-b302-ad3cda72dd83">

Make sure to whitelist your node-red instance ip in Mongodb Atlas Security > Network Access.

Make sure that your node-red instance is running at least on NodeJS v14.20.1.

I hope this helps, otherwise I need more detailed information about the error message.

**Comment by wiehannvanzyl** [comment]
Much appreciated - let me check and revert.

**Comment by steineey** [comment]
Simple and Advanced settings should not be interconnected. I have improved the code at this point to make sure that this is actually the case. Please checkout node-red-contrib-mongodb4@2.5.1
